apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bluegreen-demo
spec:
  ingressClassName: nginx
  rules:
    - host: blue-green.dev.caruso.systems
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bluegreen-demo
                port:
                  number: 80
